import {Container} from "@mui/material"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function SignUpLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Container>
      {children}
    </Container>
  )
}
