"use client"
import Header from '@/layout/Header'
import Footer from '@/layout/Footer'
import type { Metadata } from 'next'
import styled from 'styled-components'
import boxProperty from '@/fp/boxProperty'
import remsize from '@/fp/remsize'
import StyledComponentsRegistry from '@/libs/styledRegistry'
import {colors} from '@/components/Themes';
import { mediaQueries } from '@/fp/mediaQueries'
import Main  from '@/layout/Main';
import styles from '../styles/layouts/home.module.scss';
// import GlobalStyle from '@/components/Globaltyle';


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className='mainContainer'>
        <StyledComponentsRegistry>
          <div className={styles.rootLayout}>
            <Header />
            <Main>
              {children}
            </Main>
            <Footer />
          </div>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
};

 const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


