"use client"
import Header from '@/layout/Header'
import Footer from '@/layout/Footer'
import type { Metadata } from 'next'
import styled from 'styled-components'
import boxProperty from '@/fp/boxProperty'
import remsize from '@/fp/remsize'
import StyledComponentsRegistry from '@/libs/styledRegistry'
import {colors} from '@/components/Themes';
import { mediaQueries } from '@/fp/mediaQueries'
import Main  from '@/layout/Main';
// import GlobalStyle from '@/components/Globaltyle';



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <MainContainer>
            <Header />
            <Main>
              {children}
            </Main>
            <Footer />
          </MainContainer>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
};

 const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const MainContainer = styled.div`
  box-sizing: border-box;
  display: grid;

  ${mediaQueries('mobileS')(`
    ${boxProperty(`100%`,remsize(1500),'auto','0px', colors.$red)};
    grid-template-columns:repeat(10, 1fr);
    grid-template-rows: 150px auto 200px;
    grid-template-areas:
      "h h h h h h h h h h"
      "m m m m m m m m m m"
      "f f f f f f f f f f";
  `)};

  ${mediaQueries('tablet')(`
    // grid-template-rows: 80px auto 400px;

  `)};

  ${mediaQueries('laptop')(`
    ${boxProperty(`100%`,remsize(1500),'auto','0px', colors.$red)};
    grid-template-columns:repeat(10, 1fr);
    grid-template-rows: 80px auto 200px;
    grid-template-areas:
      "h h h h h h h h h h"
      "m m m m m m m m m m"
      "f f f f f f f f f f";

  `)}

`;
